### PR TITLE
Fleshes out example

### PR DESCRIPTION
**Pull request by DougReeder**
* RootModel uses Map instead of POJSO, so order remains identical
* creates avatar from template when each user joins, removes when user exits
* Updates A-Frame version

### CODE REVIEW

**Comment by NikolaySuslov** [comment]
Doug, thanks for making avatars! To satisfy the default Croquet rate event limitation (20 evt .per sec) I added a throttle function on emitting a position change from tick, instead of direct call from look-controls. Also, to eliminate a 'jitter effect' of a camera, I can suggest using a View only camera rig, controlling the position of the full Model-View avatar component, that is replicated and visible to all. Like here, implemented in VWF aka "Croquet IV" [https://livecoding.space/w/aframe2](https://livecoding.space/w/aframe2)

**Comment by DougReeder** [comment]
Thanks! It wasn't clear how to throttle the events, and I wasn't sure how to handle the jitter.

**Comment by DougReeder** [comment]
Which part of https://livecoding.space/w/aframe2?k=J1GaNakoYmYuhRhm has the view only camera rig?

**Comment by NikolaySuslov** [comment]
Hello Doug! Yes, I pointed to this as one possible solution for Avatar implementation in Croquet architecture in general. May be more better to look at Croquet Microverse Avatar implementation for sure (https://github.com/croquet/microverse/blob/8c5e92c4a7cf3a7cf650d9064645ca693d41d46f/src/avatar.js).
By "view only" I mean initialising a specialised local-only-to-user a-frame entity (camera rig in general) in RootView i.e. It is not created for others on addUser, as only an avatar body entity is created for other connected users. That worked for me in LiveCoding.space, which uses A-Frame components too. Although it is based on VWF (Croquet IV), it shares the same principles on developing Croquet applications. The concrete code of initialising local Avatar is here https://github.com/NikolaySuslov/livecodingspace/blob/c79d33f2bcdc5d97785c8c8b77611501e98a9c5c/public/drivers/view/aframe.js#L954
So, the user will interact with all replicated Model-View components through it.
In LiveCoding.space on Avatar when enters the space ( https://livecoding.space/w/aframe2) the local avatarControl entity is created, then its avatar body is created as Model-View entity for all other participants. In the view update loop (on tick) it updates avatar body position/rotation etc. Also the interpolation is applied locally to the avatar body with  https://github.com/NikolaySuslov/livecodingspace/blob/master/public/drivers/model/aframe/addon/aframe-interpolation.js smoothing animation.

**Comment by NikolaySuslov** [comment]
And to be more clear, in the view update loop (on tick) it updates avatar body position/rotation through getting current pos/rot from local-rig; then publishing events with that data; then receiving back (as other peers), updating a Model and only then actually applying it to the avatar body view and observing visually.

**Pull request merged**
